version: "3"
services:
    #PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: php:8.2-fpm
        container_name: app_laravel_cms
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - laravel-cms-network
    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver_laravel_cms
        tty: true
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "80:80"
            - "4431:443"
        networks:
            - laravel-cms-network
    #MySQL Service
    db:
        volumes:
            - db_laravel_cms:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        image: mysql:8
        container_name: db_laravel_cms
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: db_laravel_cms
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel-cms-network
    adminer:
        image: adminer
        ports:
            - 8080:8080
        networks:
            - laravel-cms-network
        depends_on:
            - db

#Docker Networks
networks:
    laravel-cms-network:
        driver: bridge
volumes:
    db_laravel_cms:
        driver: local
